# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: coffee_order.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'coffee_order.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x63offee_order.proto\" \n\x12\x43offeeOrderRequest\x12\n\n\x02id\x18\x01 \x01(\x03\"#\n\x11UserOrdersRequest\x12\x0e\n\x06userId\x18\x01 \x01(\x03\"k\n\x13\x43offeeOrderResponse\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0e\n\x06userId\x18\x02 \x01(\x03\x12\x15\n\ringredientIds\x18\x03 \x03(\x03\x12\x11\n\tcreatedAt\x18\x04 \x01(\t\x12\x0e\n\x06status\x18\x05 \x01(\t\"A\n\x18\x43reateCoffeeOrderRequest\x12\x0e\n\x06userId\x18\x01 \x01(\x03\x12\x15\n\ringredientIds\x18\x02 \x03(\x03\"@\n\x19\x43reateCoffeeOrderResponse\x12#\n\x05order\x18\x01 \x01(\x0b\x32\x14.CoffeeOrderResponse\"?\n\x17\x43offeeOrderListResponse\x12$\n\x06orders\x18\x01 \x03(\x0b\x32\x14.CoffeeOrderResponse2\xd6\x01\n\x12\x43offeeOrderService\x12\x39\n\x0cGetOrderById\x12\x13.CoffeeOrderRequest\x1a\x14.CoffeeOrderResponse\x12?\n\x0fGetOrdersByUser\x12\x12.UserOrdersRequest\x1a\x18.CoffeeOrderListResponse\x12\x44\n\x0b\x43reateOrder\x12\x19.CreateCoffeeOrderRequest\x1a\x1a.CreateCoffeeOrderResponseB2\n\x1c\x63om.example.coffeehouse.grpcB\x10\x43offeeOrderProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'coffee_order_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\034com.example.coffeehouse.grpcB\020CoffeeOrderProtoP\001'
  _globals['_COFFEEORDERREQUEST']._serialized_start=22
  _globals['_COFFEEORDERREQUEST']._serialized_end=54
  _globals['_USERORDERSREQUEST']._serialized_start=56
  _globals['_USERORDERSREQUEST']._serialized_end=91
  _globals['_COFFEEORDERRESPONSE']._serialized_start=93
  _globals['_COFFEEORDERRESPONSE']._serialized_end=200
  _globals['_CREATECOFFEEORDERREQUEST']._serialized_start=202
  _globals['_CREATECOFFEEORDERREQUEST']._serialized_end=267
  _globals['_CREATECOFFEEORDERRESPONSE']._serialized_start=269
  _globals['_CREATECOFFEEORDERRESPONSE']._serialized_end=333
  _globals['_COFFEEORDERLISTRESPONSE']._serialized_start=335
  _globals['_COFFEEORDERLISTRESPONSE']._serialized_end=398
  _globals['_COFFEEORDERSERVICE']._serialized_start=401
  _globals['_COFFEEORDERSERVICE']._serialized_end=615
# @@protoc_insertion_point(module_scope)
